services:
  - type: web
    name: hantavirus-system
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120 --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.11"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: SECRET_KEY
        value: "hanta_deploy_key_2024"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_gJfDV6vW5ZGr@ep-green-flower-algjthjl-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"